import {
  BriefcaseBusiness,
  BookMarked,
  Eye,
  MessageCircle,
  Bell,
} from "lucide-react";

export const adminStats = [
  {
    icon: BriefcaseBusiness,
    description: 120,
    title: "Total Users",
    iconColor: "text-white",
    iconBg: "bg-lime-500",
    iconBorder: "border-lime-300",
    background: "bg-white",
    shadow: "shadow-lg",
  },
  {
    icon: BookMarked,
    description: 45,
    title: "Active Jobs",
    iconColor: "text-white",
    iconBg: "bg-blue-500",
    iconBorder: "border-blue-300",
    background: "bg-white",
    shadow: "shadow-lg",
  },
  {
    icon: Eye,
    description: 310,
    title: "Applications",
    iconColor: "text-white",
    iconBg: "bg-purple-500",
    iconBorder: "border-purple-300",
    background: "bg-white",
    shadow: "shadow-lg",
  },
  {
    icon: MessageCircle,
    description: 500,
    title: "Revenue",
    iconColor: "text-white",
    iconBg: "bg-emerald-500",
    iconBorder: "border-emerald-300",
    background: "bg-white",
    shadow: "shadow-lg",
  },
  {
    icon: Eye,
    description: 520,
    title: "Views Today",
    iconColor: "text-white",
    iconBg: "bg-amber-500",
    iconBorder: "border-amber-300",
    background: "bg-white",
    shadow: "shadow-lg",
  },
  {
    icon: Bell,
    description: 12,
    title: "Notifications",
    iconColor: "text-white",
    iconBg: "bg-red-500",
    iconBorder: "border-red-300",
    background: "bg-white",
    shadow: "shadow-lg",
  },
];
